### ISSUE TITLE
Any chance this will be updated to work with the latest NODE?

### ISSUE THREAD

**Issue by PlasmaSoftUK** [LukeSkywalker92/homebridge-gpio-garagedoor#1]
Looks like this was written for Node 8 and when I try and install it on a fresh install of Node 14 and Homebridge it fails to install. I've tried loads of garage door openers but this one looks like it might actually be perfect if I could get it to work.

Thanks

Plasma

**Comment by LukeSkywalker92** [comment]
Hey. I did not use this for ages =)
But please feel free to modify it to your needs...

**Comment by PlasmaSoftUK** [comment]
I've been trying ... but I don't know anything about JavaScript, I forked it and started messing with the dependencies. I bumped OnOFF package from 1.1.0 to 6.0.0. I can at least get it to install now but its fails immediately with an error:

`[28/11/2020, 17:45:56] TypeError: Class constructor Gpio cannot be invoked without 'new'
    at DoorSensorPort.GPIOPort [as constructor] (/usr/lib/node_modules/homebridge-gpio-garagedoor/lib/GPIOPort.js:23:16)
    at new DoorSensorPort (/usr/lib/node_modules/homebridge-gpio-garagedoor/lib/DoorSensorPort.js:16:16)
    at new GPIOGarageDoorAccessory (/usr/lib/node_modules/homebridge-gpio-garagedoor/lib/GPIOGarageDoorAccessory.js:24:31)
    at /usr/lib/node_modules/homebridge/src/server.ts:357:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

I guess they have changed something in the newer packages and I can't work out where the 'new' initialiser needs to go.

Plasma
